<?php
/**
 * Created by PhpStorm.
 * User: Sal
 * Date: 7/13/2017
 * Time: 10:15 PM
 */
?>

<div id="aboutME">
    <h1>A Little About Me</h1>
    <p class="aboutMeDescription">My name is Salleh Jahaf and I am a software developer. I studied at Henry Ford College in Dearborn, Michigan and earned my Associate's degree. I am
        working on earning a Bachelor's degree in Computer Science within the next two years.</p>
    <p class="LearnedLanguages">I know how to develop software using the following languages: C, C++, Java, VB.NET, HTML, XML, XAML and PHP.
        I can create databases using MS SQL and MySQL</p>
    <p class="aboutMeDescription">I will be learning additional languages and can quickly learn a language needed for developing software.</p>
</div>