<!DOCTYPE HTML>
<html>
    <title>Salleh Jahaf's Portfolio</title>
    <link rel="stylesheet" type="text/css" href="portfolioStyle.css">
    <body>

        <div id="header">

            <div id="homeNavBar">
                <ul class="navLinksLeft">
                    <li class="Link 1">
                        <a href="#">Link 1</a>
                    </li>
                    <li class="Link 2">
                        <a href="#">Link 2</a>
                    </li>
                </ul>
            </div>

        </div>

    </body>
</html>
