<!DOCTYPE HTML>
<html>
    <title>Salleh Jahaf's Portfolio</title>
    <link rel="stylesheet" type="text/css" href="portfolioStyle.css">
    <link rel="stylesheet" type="text/css" href="w3.css">
    <div id="wholePage">
    <body>

        <div id="header">

            <div id="homeNavBar">
                <ul class="navLinksLeft">
                    <li class="home">
                        <a href="index.php?page=home">Home</a>
                    </li>
                    <li class="AboutMe">
                        <a href="index.php?page=aboutme">About Me</a>
                    </li>
                    <li class="Accomplishments">
                        <a href="#">Accomplishments</a>
                    </li>
                    <li class="Projects">
                        <a href="index.php?page=projects">Projects</a>
                    </li>
                    <li class="svgTesting">
                        <a href="index.php?page=svgtesting">svgTesting</a>
                    </li>
                </ul>
            </div>

        </div>

    </body>
</html>
