<?php
/**
 * Page for displaying projects
 */



    echo '<div id="projects">
        <div id="topCard">
            <div class="w3-card-4" style="width:25%">
                <img src="images/GVScreenshot.png" alt="GV" style="width:100%">
                <div class="w3-container w3-center">
                    <p>GV Application</p>
                </div>
            </div>
        </div>
        <svg id="radialPicker" width="500" height="500">
            <line x1="0" y1="0" x2="200" y2="200" style="stroke:rgb(0,0,255);stroke-width:2" transform="translate(-30)"/>
            <circle cx="50" cy="50" r="40" stroke="#29559e" stroke-width="4" fill="none"/>
        </svg>
    </div>';
