<?php
/**
 * Page for displaying projects
 */

?>

<div id="projects">
    <div class="w3-card-4" style="width:25%">
        <img src="images/GVScreenshot.png" alt="GV" style="width:100%">
        <div class="w3-container w3-center">
            <p>GV Application</p>
         </div>
    </div>
    <svg id="radialPicker" width="100" height="100">
        <circle cx="50" cy="50" r="40" stroke="#29559e" stroke-width="4" fill="none"/>
    </svg>
</div>
