<?php
/**
 * Page for displaying projects
 */



    echo '<div id="projects">
        <div id="topCard">
            <div class="w3-card-4" style="width:25%">
                <img src="images/GVScreenshot.png" alt="GV" style="width:100%">
                <div class="w3-container w3-center">
                    <p>GV Application</p>
                </div>
            </div>
        </div>
    </div>';
