<?php
/**
 * Created by PhpStorm.
 * User: Sal
 * Date: 3/18/2018
 * Time: 5:26 PM
 */
?>

<div id="svgTesting">
    <p>This page is used for testing svg elements.</p>
    <br/>
    <p>This page will be removed when publishing website.</p>

    <svg id="testRadialPicker" width="1000" length="1000">
        <image href="images/GVScreenshot.png" x="0" y="0" width="25%" />
        <line x1="0" y1="200" x2="200" y2="450" style="stroke:rgb(0,0,255);stroke-width:2" />

    </svg>
</div>